using System.ComponentModel.DataAnnotations;
using CampusERP.Domain.Common;
using CampusERP.Shared.Enums;

namespace CampusERP.Domain.Entities;

public class LectureOverride : BaseEntity, ITenantEntity
{
    #region Tenant

    public Guid InstitutionId { get; set; }

    public Guid CampusId { get; set; }

    public Guid AcademicSessionId { get; set; }

    #endregion

    #region Related Records

    public Guid? TimetableTemplateId { get; set; }

    public Guid? CalendarEventId { get; set; }

    #endregion

    #region Override Details

    public DateOnly OverrideDate { get; set; }

    public OverrideType OverrideType { get; set; }

    [MaxLength(500)]
    public string? Reason { get; set; }

    [MaxLength(1000)]
    public string? Remarks { get; set; }

    #endregion

    #region Teacher Override

    public Guid? OriginalTeacherId { get; set; }

    public Guid? NewTeacherId { get; set; }

    #endregion

    #region Room Override

    public Guid? OriginalRoomId { get; set; }

    public Guid? NewRoomId { get; set; }

    #endregion

    #region Time Override

    public TimeOnly? OriginalStartTime { get; set; }

    public TimeOnly? OriginalEndTime { get; set; }

    public TimeOnly? NewStartTime { get; set; }

    public TimeOnly? NewEndTime { get; set; }

    #endregion

    #region Behaviour

    /// <summary>
    /// Whether attendance should be generated for this lecture.
    /// </summary>
    public bool GenerateAttendance { get; set; } = true;

    /// <summary>
    /// Automatically generated by Scheduling Engine.
    /// </summary>
    public bool IsSystemGenerated { get; set; }

    public bool IsApproved { get; set; }

    public Guid? ApprovedByUserId { get; set; }

    public User? ApprovedByUser { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public int Version { get; set; } = 1;

    #endregion

    #region Navigation

    public Institution Institution { get; set; } = null!;

    public Campus Campus { get; set; } = null!;

    public AcademicSession AcademicSession { get; set; } = null!;

    public TimetableTemplate? TimetableTemplate { get; set; }

    public CalendarEvent? CalendarEvent { get; set; }

    public Teacher? OriginalTeacher { get; set; }

    public Teacher? NewTeacher { get; set; }

    public Room? OriginalRoom { get; set; }

    public Room? NewRoom { get; set; }

    #endregion
}